// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duvyhxrxexcztuqxkvzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dnloeHJ4ZXhjenR1cXhrdnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTcwMDYsImV4cCI6MjA3MTQzMzAwNn0.0IQawLZeRM7j9nTFiuajdgb9RRCZ6eMN6z9yt2Xovfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});